version: '3.8'

services:
  api:
    image: nestjs-docker:1.0.0
    container_name: nesjs-docker
    build:
      context: .
      target: development
      dockerfile: Dockerfile.dev
    ports:
      - 3001:3001
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env.dev
    command: npm run start:dev