service: nest-serverless

plugins:
 - serverless-plugin-typescript
 - serverless-plugin-optimize
 - serverless-offline
 - serverless-plugin-include-dependencies
 - serverless-plugin-common-excludes
 - serverless-dotenv-plugin

provider:
 name: aws
 runtime: nodejs16.x

functions:
 main:
   handler: src/lambda.handler
   events:
     - http:
         method: any
         path: /{any+}